# Generated by Django 5.0.2 on 2024-02-21 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0003_alter_aparelho_aparelho_image'),
        ('users', '0002_delete_treinopernas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('qnt_series', models.IntegerField()),
                ('qnt_repetitions', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.aparelho')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trainings', models.ManyToManyField(to='users.training')),
            ],
        ),
    ]
