# Generated by Django 5.0.2 on 2024-02-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_exercicio'),
        ('users', '0004_training_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.exercicio'),
        ),
    ]
