# Generated by Django 5.0.2 on 2024-02-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_exercicio'),
        ('users', '0006_alter_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.exercicio'),
        ),
    ]
