# Generated by Django 5.0.2 on 2024-03-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_email_profile_phone_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
