# Generated by Django 5.0.2 on 2024-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='https://lh3.googleusercontent.com/pw/ABLVV87l9T3wKq137BmKlLlHYsx0Ru7pPvecLGqjqOjLWlCpM9iDgq6Xb4dNnCep6QBR4hwWzl7AOIW5kPa33zk3_jFpnI9u6HkDTb_6gFYLEiVekFZwua58Uhver_hqCXNkazB-QqE8-Y5mvF9bBBMazuY=w600-h600-s-no-gm?authuser=0', upload_to='users/'),
        ),
    ]
