# Generated by Django 5.0.2 on 2024-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://photos.fife.usercontent.google.com/pw/AP1GczNiYGMlJfOd8i9lZfMP9QTZoRMkSN-poB_wljArjiIf4MSwg5oNrwk=w600-h600-s-no-gm?authuser=2', null=True, upload_to='users/'),
        ),
    ]
