# Generated by Django 5.0.2 on 2024-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='users/default-user.jpg', upload_to='users/'),
        ),
    ]
