# Generated by Django 5.0.2 on 2024-04-30 20:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='users/default-user.jpg', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='users/'),
        ),
    ]
