# Generated by Django 5.0.2 on 2024-06-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_treinos'),
        ('users', '0024_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.treinos'),
        ),
        migrations.AlterField(
            model_name='training',
            name='qnt_repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='qnt_series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrainingComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('qnt_series', models.IntegerField(blank=True, null=True)),
                ('qnt_repetitions', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.aparelho')),
                ('treino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.treinos')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.exercicio')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
