# Generated by Django 5.0.2 on 2024-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_training_tempo_training_treino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='tempo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
