# Generated by Django 5.0.2 on 2024-06-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_training_tempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingComplex',
        ),
    ]
