# Generated by Django 5.0.2 on 2024-06-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_trainingcomplex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(choices=[('Hiper.', 'Hiper.'), ('Cond. Físico', 'Cond. Físico'), ('Perda de Peso', 'Perda de Peso'), ('Qualidade de Vida', 'Qualidade de Vida'), ('RML', 'RML')], max_length=50)),
                ('pratica_atividades', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('atividades_fisicas', models.CharField(blank=True, max_length=300, null=True)),
                ('frequencia_atividades', models.IntegerField(blank=True, null=True)),
                ('fuma', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tempo_fumante', models.CharField(blank=True, max_length=200, null=True)),
                ('qnt_cigarro', models.IntegerField()),
                ('restricao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tipos_restricao', models.CharField(blank=True, max_length=200, null=True)),
                ('medicamento', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tipos_medicamento', models.CharField(blank=True, max_length=200, null=True)),
                ('dores', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tipos_dores', models.CharField(blank=True, max_length=200, null=True)),
                ('acidente', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tipos_acidentes', models.CharField(blank=True, max_length=200, null=True)),
                ('dieta', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('alergia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('tipos_alergia', models.CharField(blank=True, max_length=200, null=True)),
                ('controle_pressao', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('pressao', models.CharField(blank=True, max_length=200, null=True)),
                ('cardiaco', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('historico_cardiaco', models.CharField(blank=True, max_length=200, null=True)),
                ('idade', models.IntegerField()),
                ('coluna', models.CharField(choices=[('Hiper-lordose cervical', 'Hiper-lordose cervical'), ('Hiper-cifose', 'Hiper-cifose'), ('Hiper-lordose lombar', 'Hiper-lordose lombar'), ('Escoliose', 'Escoliose')], max_length=200)),
                ('estatura', models.IntegerField()),
                ('pescoco', models.IntegerField()),
                ('ombro', models.IntegerField()),
                ('torax', models.IntegerField()),
                ('cintura', models.IntegerField()),
                ('abdome', models.IntegerField()),
                ('quadril', models.IntegerField()),
                ('braco_direito', models.IntegerField()),
                ('ante_braco_direito', models.IntegerField()),
                ('coxa_direito', models.IntegerField()),
                ('panturrilha_direito', models.IntegerField()),
                ('braco_esquerda', models.IntegerField()),
                ('ante_braco_esquerda', models.IntegerField()),
                ('coxa_esquerda', models.IntegerField()),
                ('panturrilha_esquerda', models.IntegerField()),
                ('imc', models.IntegerField(blank=True, null=True)),
                ('massa_corporal', models.CharField(blank=True, max_length=200, null=True)),
                ('metabolismo', models.CharField(blank=True, max_length=200, null=True)),
                ('idade_corporal', models.CharField(blank=True, max_length=200, null=True)),
                ('gordura_viceral', models.CharField(blank=True, max_length=200, null=True)),
                ('gordura', models.CharField(choices=[('Ativo', 'Ativo'), ('Sedentário', 'Sedentário')], max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
