# Generated by Django 5.0.2 on 2024-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_listaavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaavaliacao',
            name='avaliado',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Sedentário', 'Sedentário')], default='ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='listaavaliacao',
            name='gordura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
