# Generated by Django 5.0.2 on 2024-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_listaavaliacao_avaliado_alter_listaavaliacao_gordura'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avaliacoes',
            field=models.ManyToManyField(to='users.listaavaliacao'),
        ),
    ]
