# Generated by Django 5.0.2 on 2024-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_profile_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaavaliacao',
            name='controle_pressao',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], max_length=10),
        ),
    ]
