# Generated by Django 5.0.2 on 2024-06-05 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_profile_avaliacoes_anamnese_profile_anamnese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 5, 14, 13, 25, 730904)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antropometria',
            name='data_antropometria',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-05 14:30:00'),
            preserve_default=False,
        ),
    ]
