# Generated by Django 5.0.2 on 2024-06-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_anamnese_qnt_cigarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='antropometria',
            name='massa_corporal_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='abdome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='ante_braco_direito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='ante_braco_esquerda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='braco_direito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='braco_esquerda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='cintura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='coxa_direito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='coxa_esquerda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='estatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='massa_corporal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='ombro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='panturrilha_direito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='panturrilha_esquerda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='pescoco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='quadril',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antropometria',
            name='torax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
