# Generated by Django 5.0.2 on 2024-06-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='tipo_treino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='coluna',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Hiper-lordose cervical', 'Hiper-lordose cervical'), ('Hiper-cifose', 'Hiper-cifose'), ('Hiper-lordose lombar', 'Hiper-lordose lombar'), ('Escoliose', 'Escoliose')], max_length=200),
        ),
    ]
