# Generated by Django 5.0.2 on 2024-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_training_tipo_treino_alter_anamnese_coluna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='qnt_repetitions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
