# Generated by Django 5.0.2 on 2024-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='aparelho_image',
            field=models.CharField(default='https://photos.app.goo.gl/WxejAcZVZshK2xwJ6', max_length=500),
        ),
    ]
