# Generated by Django 5.0.2 on 2024-02-23 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_aparelho_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio_type', models.CharField(max_length=200)),
                ('exercicio_image', models.CharField(default='https://lh3.googleusercontent.com/pw/ABLVV87cle3nCJz8sZI9wom9p8awgyA4bfNHYPIDqzpFgfpxS7woVqYIN0KokLtQl9OXJ7D1RH0bTabUIh2b3GQm-0E-Z88c05ZgJraEYxjW8vIOZwhd7SrX1RjUg6F1O1tkB8Pc3094OPPl8XKVp2c1ulY=w980-h980-s-no-gm?authuser=2', max_length=500)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
