# Generated by Django 5.0.2 on 2024-02-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_exercicio'),
        ('users', '0006_alter_training_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
    ]
