# Generated by Django 5.0.2 on 2024-03-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_alter_aparelho_aparelho_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='aparelho_image',
            field=models.ImageField(default='media/parelhos/default.jpg', upload_to='aparelhos/'),
        ),
    ]
