# Generated by Django 5.0.2 on 2024-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_alter_aparelho_aparelho_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='exercicio_image',
            field=models.ImageField(default='exercicio/default.jpg', upload_to='exercicio/'),
        ),
    ]
