# Generated by Django 5.0.2 on 2024-06-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_treinos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='aparelho_image',
            field=models.ImageField(default='academia/aparelhos/default.jpg', upload_to='academia/aparelhos/'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='exercicio_image',
            field=models.ImageField(default='academia/exercicio/default.jpg', upload_to='academia/exercicio/'),
        ),
        migrations.AlterField(
            model_name='treinos',
            name='treino_image',
            field=models.ImageField(default='academia/treino/default.jpg', upload_to='academia/treino/'),
        ),
    ]
